### PR TITLE
Replace forkme ribbon image by pure CSS ribbon

### PR DESCRIPTION
**Pull request by bittner**
Currently, the "Fork me on GitHub" ribbon is both an image and not correctly responsive.

Provided Changes
--------------

This PR replaces the image-version of the "Fork me" ribbon by a pure CSS version. The related code has been generated at https://codepo8.github.io/css-fork-on-github-ribbon/

Current Status (Example)
------------

[docs-on-phablet-screenshot](https://pytest-django.readthedocs.io/)

Caveat
------

The [github_ribbon_color](https://github.com/pallets/flask-sphinx-themes/blob/master/flask_sphinx_themes/flask/theme.conf#L11) theme option is a victim of this change. This is because the ribbon color is now provided by the CSS.

I can provide a CSS override using the `style` attribute if it is important to keep this option. (Note that we could then also provide a `:hover` color.)

### CODE REVIEW

**Comment by bittner** [comment]
Maybe the two occurences of `.github` on [line 442](https://github.com/bittner/flask-sphinx-themes/blob/2aecf4ee23a83c9c06353f6bc8c2cecb24920fbd/flask_sphinx_themes/flask/static/flasky.css_t#L442-L444) and [line 532](https://github.com/bittner/flask-sphinx-themes/blob/2aecf4ee23a83c9c06353f6bc8c2cecb24920fbd/flask_sphinx_themes/flask/static/flasky.css_t#L532-L534) of the CSS should also be removed. Not sure though. They may have been a (failed) attempt to make the over-scaled ribbon image not display on small screens.

**Comment by davidism** [comment]
The CSS file is a template, so why can't you use the color there? Also, please undo the spacing changes your ide made, it makes it difficult to review prs.

**Comment by bittner** [comment]
@davidism Sorry for the whitespace changes caused by PyCharm. I noticed them too. The root cause, though, is that it's a flaw of the source document to have trailing whitespace, isn't it? It will happen again. As for the vertical spacing, I tried to make the spacing in the source file uniform.

If you don't mind, please review my PR [ignoring whitespace changes](https://github.com/pallets/flask-sphinx-themes/pull/16/files?w=1). Thank you for your comprehension!

I'll add another commit to restore the color option.

**Comment by davidism** [comment]
Please make a separate PR if you'd like to make style changes.

**Comment by davidism** [comment]
In the future, please make style changes in a separate PR. I understand that you can ignore whitespace in diffs, and I have no problem with fixing style issues, but for simplicity these should be separate.

**Comment by bittner** [comment]
> In the future, please make style changes in a separate PR.

Does that mean you're happy with the PR as it is? :hushed:  Thanks bunches! :relieved:

Again, I'm sorry for the whitespace changes. They were not deliberate changes. I usually try to put changes like those into separate PRs, or at least separate commits.

Thanks in advance  for merging!
I'm looking forward to enjoying the pure CSS ribbon on my phone! :smiley:

**Comment by bittner** [comment]
Anything needed to make this PR being merged?

**Comment by bittner** [comment]
If there is anything I can do to help this PR getting merged please let me know!

**Comment by bittner** [comment]
Anything needed to make you merge this PR?

**Comment by davidism** [comment]
I've been playing around with this. I just don't find the CSS replacement to look nearly as good as the image, even zoomed in. Also, I don't observe the weird scaling behavior you describe. I tried Safari on iPhone 5, and Firefox and Chrome on a Nexus 6p. It also looks fine in the mobile view for iPhone 6 on desktop Chrome and Firefox.

I'll see about adding a responsive break to make the image less disruptive on mobile. However, if you want to replace it I want to see a solution that looks closer to the image, but I'm not familiar enough with CSS to adjust that.6

**Pull request closed without merging**
